import pytest
import proj1
import csv

# makes sure the sample output provided is the same as the output generated by my code
def test_generate_data():
    proj1.generate_data()
    myrows = []
    herrows = []

    with open('summary-results.csv') as csvfile:
        rows = csv.reader(csvfile)

        for row in rows:
            myrows.append(row)

    with open('./sample-files/sumary-results.csv') as csvfile:
        rows = csv.reader(csvfile)

        for row in rows:
            herrows.append(row)

    myrows.sort()
    herrows.sort()

    for i in range(len(myrows)):
        assert myrows[i] == herrows[i]
