import pytest
import proj2
import csv


class Args():
    def __init__(self, json_file, output_filename, time_str_format, human_readable):
        self.json_file = json_file
        self.output_filename = output_filename
        self.time_str_format = time_str_format
        self.human_readable = human_readable


@pytest.fixture
def args():
    args = Args(
            ['write-8k.json', 'write-1M.json', 'read-8k.json', 'read-1M.json', 'rw70-8k.json', 'rw70-1M.json', 'rw50-8k.json', 'rw50-1M.json'],
            'random_test.csv',
            '%Y-%m-%d %H:%M:%S',
            False
        )

    return args


# makes sure the sample utc file provided is the same as the output generated by my code with the same parameters
def test_generate_data(args):
    proj2.generate_data(args)
    myrows = []
    herrows = []

    with open(args.output_filename) as csvfile:
        rows = csv.reader(csvfile)

        for row in rows:
            myrows.append(row)

    with open('./sample-files/sumary-results-utctime.csv') as csvfile:
        rows = csv.reader(csvfile)

        for row in rows:
            print(row)
            herrows.append(row)

    myrows.sort()
    herrows.sort()

    for i in range(len(myrows)):
        assert myrows[i] == herrows[i]
